### ISSUE TITLE
refatorar o codigo de matar cobra e gerar snacks no board

### ISSUE THREAD

**Issue by pauloamed** [pauloamed/KobraFight#10]

**Comment by gabriel-igorq** [comment]
def checkCollisions(self):
        badBlocks = {}
        for snake in self.snakes.values():
            if snake.alive:
                for c in snake.body:
                    if c.pos in badBlocks:
                        badBlocks[c.pos] += 1
                    else:
                        badBlocks[c.pos] = 1

        for snake in self.snakes.values():
            if snake.alive:
                if badBlocks[snake.body[0].pos] > 1:
                    # snake.alive = False
                    self.addSnack([c.pos for c in snake.body])
                    snake.die()
                # snake.reset(self.getValidPos())

        del badBlocks
